# Personal Portfolio Website

## Description
A modern, responsive portfolio website showcasing academic achievements, work experience, and projects in Machine Learning and Data Science.

## Features
- Responsive design for all devices
- Modern UI with smooth animations
- Interactive project showcase
- Contact form integration
- SEO optimized

## Technologies
- HTML5
- CSS3 (Flexbox/Grid)
- JavaScript (ES6+)
- Font Awesome Icons
- Google Fonts

## Setup
1. Clone or download the files
2. Open `index.html` in a web browser
3. Customize content in HTML files
4. Modify styles in `styles.css`
5. Deploy to GitHub Pages or any web hosting service

## File Structure
- `index.html` - Main website file
- `styles.css` - All styling and responsive design
- `script.js` - Interactive functionality
- `README.md` - Project documentation

## Customization
- Update personal information in `index.html`
- Modify colors and fonts in `styles.css`
- Add your resume PDF file
- Update social media links
- Customize project descriptions and links

## Deployment
Perfect for GitHub Pages deployment. Simply upload to a repository named `yourusername.github.io`

## License
Free to use and modify for personal portfolios.